move the algod client to store
TxnLab/use-wallet pull request #224
Opened 2024-08-29 20:35 UTC by acfunk

This is to address issue #213 

- replaced the `algodClient` prop on the `WalletManager` with a getter and setter that point to the `store`
- removed `algodClient` from persisted storage - the re-serialization makes it useless anyway
- `setActiveNetwork` on `store` now takes `algodClient` as a parameter
- tests were updated to reflect the changes

2024-08-30 13:15 UTC, drichar requested changes
Appreciate you splitting this from your other PR so the changes can be addressed separately. Overall this looks good, and most of my change requests are minor optimizations. The important one is making sure `loadPersistedState` has the correct return type.

While this does handle moving the algod client to the store in the core library, I'm curious whether this now works as expected in your Vue app (AlgoTools)? When @SilentRhetoric made [his PR](https://github.com/TxnLab/use-wallet/pull/204) to fix network switching in the Solid adapter, the critical change was moving the algod client to the `@tanstack/solid-store` _reactive_ store.

The way he described it to me, I would have expected something similar to get it working properly in the Vue adapter: accessing the `algodClient` like this:
```ts
const algodClient = useStore(manager.store, (state) => state.algodClient)
```
and having that be what's returned from its `useWallet` composable function.

That's what I was planning to do in the Vue and React adapters when I created https://github.com/TxnLab/use-wallet/issues/213. Your changes here were also needed! I was just expecting the framework-specific reactive stores to also be part of the solution.

2024-08-30 13:15 UTC, drichar commented on packages/use-wallet/src/manager.ts
> +      const parsedState = JSON.parse(serializedState) as Omit<State, 'algodClient'>
You're casting `parsedState` as `Omit<State, 'algodClient'>` but then casting it back to `State` in the return statement. The return type of this method should be updated to reflect what's actually being returned. You could define (perhaps in store.ts)
```ts
export type PersistedState = Omit<State, 'algodClient'>
```
then have `loadPersistedState` return `PersistedState | null`.

This will affect the way `initialState` is defined in the manager's constructor. You'll have to start with a `PersistedState | null` type and then assemble a `State` object containing the algod client to initialize the store.

2024-08-30 13:15 UTC, drichar commented on packages/use-wallet/src/manager.ts
> +  }
Minor stylistic request: only properties defined before the `constructor`, then methods and derived properties (getters and setters) should follow

2024-08-30 13:15 UTC, drichar commented on packages/use-wallet/src/manager.ts
> +      delete state.algodClient
You had asked me about using `delete` here. I think this is fine for now, but once the `PersistedState` type is defined, I may update this to use destructuring instead, and avoid casting `as any`. Since it'll also require updating the ESLint config to allow for exceptions to the `no-unused-vars` rule, it can be done later after this is merged.

2024-08-30 13:15 UTC, drichar commented on packages/use-wallet/src/store.ts
> +  algodClient: Algodv2
For consistency with other state mutation functions (see `addWallet` and `setActiveAccount`), the second argument should be a single object containing all the store properties being updated.
```suggestion
  { networkId, algodClient }: { networkId: NetworkId; algodClient: Algodv2 },
```

2024-08-30 17:05 UTC, acfunk commented on packages/use-wallet/src/manager.ts
> +      delete state.algodClient
I used destructuring here.

2024-08-30 17:07 UTC, acfunk commented on packages/use-wallet/src/manager.ts
> +      const parsedState = JSON.parse(serializedState) as Omit<State, 'algodClient'>
Vue reactivity is handled in `WalletManagerPlugin` with `const algodClient = ref(manager.algodClient)`.
I'll take a look at React.

2024-08-30 17:09 UTC, acfunk commented
> That's what I was planning to do in the Vue and React adapters when I created #213. Your changes here were also needed! I was just expecting the framework-specific reactive stores to also be part of the solution.

Vue reactivity is handled in `WalletManagerPlugin` with `const algodClient = ref(manager.algodClient)`.
I'll take a look at React.

2024-09-03 21:50 UTC, drichar commented on packages/use-wallet/src/manager.ts
> +      delete state.algodClient
Sorry that was vague. I meant something like this
```ts
const { algodClient: _, ...serializableState } = this.store.state
```
with an ESLint setting that makes exceptions for `no-unused-vars` if the variable name starts with (or is) an underscore.

2024-09-03 21:52 UTC, drichar approved these changes
Looks great! LGTM

2024-09-03 21:54 UTC, merged